# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: environment
    displayName: Environment
    type: string
    values: ["sandbox"]

variables:
  backendrg: 'pnlabs-tfstate-rg'
  backendst: 'pnlabstfstatest'
  bkcontainer: 'tfstate'
  bkstkey: 'pnlabs.tfstate'

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environments/${{ parameters.environment }}'
              backendServiceArm: 'pnlabs_pipeline_serviceconnection'
              backendAzureRmResourceGroupName: '$(backendrg)'
              backendAzureRmStorageAccountName: '$(backendst)'
              backendAzureRmContainerName: '$(bkcontainer)'
              backendAzureRmKey: '$(bkstkey)'
          - task: TerraformTaskV4@4
            displayName: validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environments/${{ parameters.environment }}'
  - stage: tfdeploy
    condition: succeeded('tfvalidate')
    dependsOn: tfvalidate
    jobs:
      - job: apply
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environments/${{ parameters.environment }}'
              backendServiceArm: 'pnlabs_pipeline_serviceconnection'
              backendAzureRmResourceGroupName: '$(backendrg)'
              backendAzureRmStorageAccountName: '$(backendst)'
              backendAzureRmContainerName: '$(bkcontainer)'
              backendAzureRmKey: '$(bkstkey)'
          - task: TerraformTaskV4@4
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environments/${{ parameters.environment }}'
              environmentServiceNameAzureRM: 'pnlabs_pipeline_serviceconnection'
          - task: TerraformTaskV4@4
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environments/${{ parameters.environment }}'
              environmentServiceNameAzureRM: 'pnlabs_pipeline_serviceconnection'
