name: Terraform_Destroy

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        required: true
        description: 'Choose which environment you want to deploy'
        default: 'sandbox'
        options:
          - sandbox
          - dev
          - qa
          - production


jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.name }}

    defaults:
      run:
        shell: bash
        working-directory: ./environments/${{ github.event.inputs.name }}

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2.0.3

      - name: 'Terraform Init'
        id: init
        run: terraform init

      - name: 'Terraform Destroy'
        id: destroy
        run: terraform destroy --auto-approve
