name: Terraform

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        required: true
        description: 'Choose which environment you want to deploy'
        default: 'sandbox'
        options:
          - sandbox
          - dev
          - qa
          - production


jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: sandbox

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2.0.3

      - name: 'Terraform Format'
        id: fmt
        run: terraform fmt
        continue-on-error: true

      - name: 'Terraform Init'
        id: init
        run: terraform init
        working-directory: ./environments/${{ github.event.inputs.name }}

      - name: 'Terraform Validate'
        id: validate
        run: terraform validate
        working-directory: ./environments/${{ github.event.inputs.name }}

      - name: 'Terraform Plan'
        id: plan
        run: terraform plan
        continue-on-error: true
        working-directory: ./environments/${{ github.event.inputs.name }}

      - name: 'Terraform Apply'
        id: apply
        run: terraform apply --auto-approve
        working-directory: ./environments/${{ github.event.inputs.name }}
